apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: it25b/gateway
          env:
          - name: 
            valueFrom: MONGO_ROOT_PW
              secretKeyRef:
                name: auth-secret
                key: MONGO_ROOT_PW
          - name: MONGO_USER
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: MONGO_USER