apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 4
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: it25b/notification
          env:
          - name: GMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notification-secret
                key: GMAIL_PASSWORD
          - name: GMAIL_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: notification-configmap
                key: GMAIL_ADDRESS
          - name: MP3_QUEUE
            valueFrom:
              configMapKeyRef:
                name: notification-configmap
                key: MP3_QUEUE