apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: it25b/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-mysql
          image: mysql:8.0 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: MYSQL_ROOT_PW
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: MYSQL_DB
          - name: MYSQL_USER 
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: MYSQL_PASSWORD
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: mongo-db
          image: mongo
          env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: MONGO_ROOT_PW
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: MONGO_USER
          ports:
          - containerPort: 27017
            name: mongo-db
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim