apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: Auth123
  MONGO_ROOT_PW: my-secret-password123
  MYSQL_ROOT_PW: my-secret-password123
  JWT_SECRET: sarcasm
type: Opaque
