apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql
  labels:
    app: auth
spec:
  ports:
    - port: 3306
  selector:
    app: auth
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: auth
spec:
  ports:
    - port: 27017
  selector:
    app: auth
  clusterIP: None